In [31]:
import numpy as np


d=2 #numero de variables de entrada
M=2 #grado del polinomio
k=3 #(d*(M+1)) # K es la cantida de parametros (w) a encontrar, (M+1) es la cantidad de coeficientes


X = np.random.randint(0,10,(3,d+1))
w = np.ones(3).reshape(3, 1)
#tem = np.dot(X.T,w)

print (X)

[[3 8 9]
 [5 7 4]
 [3 2 3]]
