In [18]:
import numpy as np


d=2 #numero de variables de entrada
M=2 #grado del polinomio
k=(d*(M+1)) # K es la cantida de parametros (w) a encontrar, (M+1) es la cantidad de coeficientes


X = np.random.randint(0,10,(10,d+1))
W = np.ones(k).reshape(k, 1)
print (x)

[[7 6 8]
 [2 7 8]
 [0 8 1]
 [3 5 9]
 [8 4 3]
 [8 8 7]
 [3 7 3]
 [9 2 3]
 [5 6 1]
 [0 5 0]]
